version: '3.4'

services:
  googlespeechukrbotrunner:
    image: ${DOCKER_REGISTRY-}googlespeechukrbotrunner
    build:
      context: .
      dockerfile: GoogleSpeechUkrBotRunner/Dockerfile

  googlespeechukrbotworker:
    image: ${DOCKER_REGISTRY-}googlespeechukrbotworker
    build:
      context: .
      dockerfile: GoogleSpeechUkrBotWorker/Dockerfile

